### ISSUE TITLE
Erroneous iblank labeling from TIOGA in Nalu-Wind domain

### ISSUE THREAD

**Issue by mbkuhn** [Exawind/exawind-driver#65]
TIOGA incorrectly labels some fringe points as field points in the Nalu-Wind domain. In single-phase simulations, this causes lack of convergence in AMR-Wind solvers and significant slowdown; in two-phase simulations it leads to rapid growth of velocity and crashing. The specific errors depend on the number of processors used by Nalu-Wind and the type of decomposition used (rcb, parmetis), e.g. more processors leads to more errors, and parmetis reduces the number of erroneous points but does not reliably eliminate them. The attached single-phase example shows this issue in a simple, small case that can be run locally. The Nalu-Wind domain is a rectangular box of uniform resolution that has been rotated 30 degrees. It lies within an AMR-Wind domain, and the initial condition and case setup is a uniform flow. By allocating only a single processor to Nalu-Wind, no iblank issues arise, but with non-unity processors the decomposition process introduces errors.

Using a non-rotated domain that is specified directly from the Nalu-Wind input file results in no iblank issues; however, a non-rotated domain from an Exodus file will still lead to iblank issues if enough decomposition is required.

[TiogaNaluIssues.tar.gz](https://github.com/Exawind/exawind-driver/files/14014547/TiogaNaluIssues.tar.gz)

**Comment by michaelasprague** [comment]
![iblank_slicey0_aw1_nw7](https://github.com/Exawind/exawind-driver/assets/2040708/8bc12a85-bf1a-4a4e-948c-dea3553369af)

Example from Michael's tarball for easy reference

**Comment by itopcuoglu** [comment]
The PR by Phil addresses the anomaly in the iblank field, though we need a parallel_min operation instead of parallel_max since we want to set the iblank to -1 in Nalu-Wind if any Tioga rank has set it to -1 at all. When we ran the test problem with parallel_min, we saw that it corrected the iblank field, and the artifacts near the outer boundary disappeared in the iblank plot. Concurrently, this causes the hybrid solver to crash. 

This is likely because while the modification fixes the iblank field, no field value is interpolated to that cell in Tioga since it was classified as a field point (iblank=1), and not a receptor/fringe point (iblank=-1). So the fix has to happen inside Tioga, and it has to ensure that duplicate nodes at STK mesh partition boundaries have the same iblank values prior to linear interpolation of field values to receptor cells.

**Comment by psakievich** [comment]
@itopcuoglu @mbkuhn can we close this issue? I believe it has all been resolved correct?

**Comment by mbkuhn** [comment]
Yes, we can close it. However, we've found a new issue that appears to be related.

**Comment by psakievich** [comment]
> Yes, we can close it. However, we've found a new issue that appears to be related.

Oh joy...
